#!/bin/sh

export MACOS_SCRIPTS_DIR=`pwd`
export LL_ROOT=${MACOS_SCRIPTS_DIR}/../..
export MOBILE_LIB_ROOT="${MACOS_SCRIPTS_DIR}"/mobileliblelantus
export EXTERNAL_MACOS_DIR="${LL_ROOT}/macos"
export EXTERNAL_MACOS_SOURCE_DIR=${EXTERNAL_MACOS_DIR}/sources
export EXTERNAL_MACOS_LIB_DIR=${EXTERNAL_MACOS_DIR}/lib
export EXTERNAL_MACOS_INCLUDE_DIR=${EXTERNAL_MACOS_DIR}/include

mkdir -p $EXTERNAL_MACOS_LIB_DIR
mkdir -p $EXTERNAL_MACOS_INCLUDE_DIR
mkdir -p $EXTERNAL_MACOS_SOURCE_DIR